### ISSUE TITLE
Update license for project

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#1]
We have recently changed the license for this project to the [AGPL License](https://www.gnu.org/licenses/agpl-3.0.en.html). This change affects how users and contributors can use and contribute to the project. Before continuing to use or contribute to the project, please review the new license carefully. If you have any questions or concerns about the license change, please don't hesitate to reach out to us. We appreciate your continued support and contributions to the project.

**Comment by Saloni581** [comment]
May I work on this issue under GSSoC'23.

**Comment by royalpinto007** [comment]
The issue has already been resolved, thanks!
