### ISSUE TITLE
Integrating get in touch section with backend

### ISSUE THREAD

**Issue by tushar-glitch** [Stoccoin-Official/Stoccoin-Website#100]
I can integrate the get in touch section with the backend so that the user data can get saved in the database and additionally, I can also put validations in the frontend section.

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by RazzaqShikalgar** [comment]
I would like to contribute to this repo as a part of GSSOC'23
Please Assign me this issue !! I can do it and can add more extra features !!
