### ISSUE TITLE
Social links in footer should open in new tab

### ISSUE THREAD

**Issue by MahendraDani** [Stoccoin-Official/Stoccoin-Website#102]
## Description
1. It is considered to be a good convention if the third-party links open in a new tab.
2. The link of instagram handle is broken.

## Files to reproduce this issue
- client/components/Footer.jsx

## Screenshots/Video

https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/406c8ce5-99e3-4e5b-aa54-fd3f84ecb233

- I would like to work on this issue.

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by MahendraDani** [comment]
@Sathvik902 I raised a PR for this issue and I am also contributing under GSSoC'23.
Please try to resolve other open issues.
Thanks for showing interest.

**Comment by MahendraDani** [comment]
@royalpinto007 
- If you could provide the correct link for the instagram handle, I can add it another PR.
- Should I add icons of the social handles with proper hover effects and functionality or the existing is fine?

Thanks!

**Comment by royalpinto007** [comment]
Hi @MahendraDani,
Thank you for addressing this issue. 

Regarding the Instagram link, it appears to be working correctly. If you are unable to access it, please consider switching your network. 
Additionally, an issue has already been created for the icons. You can contribute to the existing issue to help resolve it.

Please let me know if you need further assistance. 
Thanks!
