### ISSUE TITLE
Add hover effects to links in navbar

### ISSUE THREAD

**Issue by MahendraDani** [Stoccoin-Official/Stoccoin-Website#104]
## Description
1. The mobile and tablet navigation bar has hover effects on the links.
2. Similar hover effect on nav links is required.

## Screenshots/Video

https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/2e2b7b31-f773-4e2c-a22c-ac9884c9c711

- I would like to work on this issue.

**Comment by MahendraDani** [comment]
@royalpinto007 If there are any changes required in the UI please let me know.
Thanks!

**Comment by khubaibkm** [comment]
Hello, I am a GSSOC Contributor and want to work on this issue.

**Comment by Aarav238** [comment]
I would like to work on it.  Please assign this to me

**Comment by endeavourmonk** [comment]
I would like to work on this issue under GSSOC'23. Please assign it to me.

**Comment by royalpinto007** [comment]
Hi @khubaibkm, @Aarav238 and @endeavourmonk, 
The issue has already been solved at https://github.com/Stoccoin-Official/Stoccoin-Website/pull/154 by @MahendraDani!
You guys can look at other issues present in the issue queue :)
Thanks for understanding!
