### ISSUE TITLE
Adding hover and shadow effects to pricing cards

### ISSUE THREAD

**Issue by mukul314** [Stoccoin-Official/Stoccoin-Website#107]
Currently, when we hover over the pricing cards, nothing happens. If we tweak the CSS a little bit then we can make them increase their scale and also add a shadow when hovered upon. This will make the website more eye catchy. See the below video for reference.

https://github.com/Stoccoin-Official/Stoccoin-Website/assets/76463001/1cf4ce0d-325e-47bb-88b4-2981638ce275

I'd be happy to work on this if you assign me this task @royalpinto007 !!!

**Comment by royalpinto007** [comment]
Cool, please submit a PR for the same. 
Thanks!
