### ISSUE TITLE
[FEAT] Custom Error Page 404

### ISSUE THREAD

**Issue by virajchandra51** [Stoccoin-Official/Stoccoin-Website#111]
I will design an Error Page for calls or redirecting to pages which do not exist.

Hello!
I am Viraj Chandra, a proud contributor at GSSoC '23. I would like to the contribute to this project by designing an Error Page for calls or redirecting to pages which do not exist.

Things I will be doing as of now:
- [ ]  Designing the error page 404

@royalpinto007 Please Assign me this.

**Comment by royalpinto007** [comment]
Hi @virajchandra51, thanks for bringing this up!
Looking forward to your contribution :)

**Comment by Vaibhav-Sharma010204** [comment]
hi @virajchandra51 
i would love to work on this kindly assign this to me

**Comment by Vaibhav-Sharma010204** [comment]
hello @royalpinto007 
i would love to work on this 
kindly assign it to me
