### ISSUE TITLE
[Education] Add education content for stoccoin #216

### ISSUE THREAD

**Issue by sabhisharma-ise** [Stoccoin-Official/Stoccoin-Website#114]
The stoccoin repo currently does not have any education content. This makes it difficult for users to learn how to use the application. Adding education content would help users to learn how to use the application and to get the most out of it.

By adding education content to the stoccoin repo, we can help users to learn how to use the application and to get the most out of it.

Please assign this issue to me!

Contributor - Sabhi Sharma (GSSOC'23)

**Comment by royalpinto007** [comment]
Hi @sabhisharma-ise, appreciate your effort in bringing this up, however issue for this has already been created at https://github.com/Stoccoin-Official/Stoccoin-Website/issues/10. Maybe, you can try to solve something there :)
Thanks for understanding!
