### ISSUE TITLE
[Enhancement] Adding SMTP server to Form section

### ISSUE THREAD

**Issue by pooranjoyb** [Stoccoin-Official/Stoccoin-Website#122]
## Description
I would like to add an `SMTP` endpoint to the `Newsletter` section.

## Outcomes : 
- The information will be diverted to the user's email address directly through the redirections of the website.
- **NodeJS & some external libraries could be required**

## Implementation : 
- I will be creating an SMTP server using NodeJs and connect user requests to the backend. This will send mails to the owner of the repository.
- Hence, providing info about the users interested in Newsletter Subscriptions.

## Screenshots : 
![1](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/90945182/6b89afa5-699f-4485-a36a-9ebb74a14a04)

### I would like to work on this issue under GSSoC 2023. Please assign 😄 @royalpinto007

**Comment by royalpinto007** [comment]
Hi @pooranjoyb, please submit a PR, thanks!

**Comment by pooranjoyb** [comment]
Getting into it asap, Thanks! @royalpinto007 🚀

**Comment by pooranjoyb** [comment]
Hey, @royalpinto007 
Here's an update:
I've also worked out with the contact form. 
Now once user fills the form, and sends, the backend will send mail to your email. This is more efficient as we can track the mails sent and received from the email itself. I'll create another issue for the newsletter too. Till then please review the PR and merge it.
