### ISSUE TITLE
Add Social Media Handles to README

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#13]
As a project team, we would like to add our social media handles to the README file to help promote our project and increase our online presence. By including links to our social media accounts, users and potential contributors can easily follow us and stay updated on project news and updates. This will also provide a way for users to engage with us and ask questions or provide feedback about the project. Adding social media handles to the README file will help us to build a community around the project and increase its visibility on social media platforms.

**Comment by munnokd** [comment]
Can I work on this issue?

**Comment by royalpinto007** [comment]
Sure, please go ahead.

**Comment by munnokd** [comment]
Thanks @royalpinto007 for assigning this issue to me. Please provide your social media links so I will add them to readme.

**Comment by royalpinto007** [comment]
Instagram- https://www.instagram.com/stoccoin/
Twitter- https://twitter.com/stoc_coin
LinkedIn- https://www.linkedin.com/company/stoccoin/

**Comment by munnokd** [comment]
Thank you I will update it.

**Comment by munnokd** [comment]
I added pr. Please check it.

**Comment by munnokd** [comment]
Hey @royalpinto007  I added pr please review that pr.

**Comment by royalpinto007** [comment]
Thanks!
