### ISSUE TITLE
Website is Not Responsive

### ISSUE THREAD

**Issue by SubhamB2003** [Stoccoin-Official/Stoccoin-Website#138]
Hey, I want to work on this. Can you please assign it to me?

You can see the issue
![image](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/94003231/37d85c7d-38e1-4780-affc-91c257fecc5a)

After Solving the issue
![image](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/94003231/6fc11c34-e246-4db3-b94e-8c53438549e5)

**Comment by royalpinto007** [comment]
Hi @SubhamB2003,
The issue is already being addressed. 
Thanks for bringing this up :)

**Comment by SubhamB2003** [comment]
> Hi @SubhamB2003, The issue is already being addressed. Thanks for bringing this up :)

Hey, Is it already solved?
if not can you assign it to me?
