### ISSUE TITLE
Update README to Redirect to CONTRIBUTING.md

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#14]
Our project README currently includes a section for contributing guidelines, but we want to improve the organization of our project by moving the contributing guidelines to a separate file. This will help to streamline the README and make it easier for users to navigate.

To achieve this, we need to update the README file to include a link or redirect to the CONTRIBUTING.md file, which will contain all the contributing guidelines. By doing so, users will be directed to the appropriate location for information on how to contribute to our project.

This change will help to improve the clarity and organization of our project documentation, making it easier for users to engage with our project and contribute to its success.

**Comment by raghav515** [comment]
Can I work on this issue?

**Comment by royalpinto007** [comment]
Sure, please go ahead.

**Comment by MahendraDani** [comment]
@royalpinto007 
This issue is stale and the assigned contributor has not yet fixed this issue.
Will it be fine if I fix this issue?

**Comment by royalpinto007** [comment]
@MahendraDani 
Yeah cool, please go ahead!
