### ISSUE TITLE
Make the Contact From Working

### ISSUE THREAD

**Issue by kapil4457** [Stoccoin-Official/Stoccoin-Website#140]
@royalpinto007  I am a contributor under GSSOC 2023.....I will use Email.js and make the contact form work..Please assign me this issue

**Comment by RazzaqShikalgar** [comment]
@royalpinto007 i can sort this issue asap !! please assign me this issue

**Comment by kapil4457** [comment]
> @royalpinto007 i can sort this issue asap !! please assign me this issue

Bro I raised this issue so that I can work on it...please don't comment on issues raised by others...instead find an issue which no one has raised yet and then raise it...
