### ISSUE TITLE
Adding Preloading Screen

### ISSUE THREAD

**Issue by SubhamB2003** [Stoccoin-Official/Stoccoin-Website#142]
Hey, Can I add the preloading screen on the website, It's always showing the animation screen before the actual page is loaded
Here is a demo animation
https://github.com/DevFeed404/DevFeed-1.0/assets/94003231/be7ee74a-78dc-45b7-b532-f1a6478a84d0

I want to work on this feature. Please assign it to me under GSSOC 23.

**Comment by SubhamB2003** [comment]
@royalpinto007 Hey, can I work on it?

**Comment by Visbhavesh** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.
