### ISSUE TITLE
Login/SignUp Page

### ISSUE THREAD

**Issue by johnwick1212** [Stoccoin-Official/Stoccoin-Website#159]
currently there is no login and signup page.
I am thinking of making one, can you assign this to me?

**Comment by PrathamAsrani** [comment]
Dear Team,
I would like to create a login/SignUp page integrated with Backend with user authentication. Please assign me the respectove work @johnwick1212

**Comment by ayushrathore111** [comment]
I would like to work on this could you please assign  to me... 
#98 @johnwick1212 @PrathamAsrani

**Comment by niranjan-kurhade** [comment]
I wanted to work on the Frontend Part of the Login/Signup page. Can I work on this @royalpinto007 ? And is this issue under part of GSSOC'23?
