### ISSUE TITLE
Text Visibility Issue in Newsletter Subscription Form

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#161]
When users type in their email to subscribe to the newsletters, the text and background color of the input field are the same, resulting in poor visibility. As a result, the entered text is not easily readable, which can lead to user frustration and a negative experience.

This issue requires fixing the text and background color of the input field to ensure proper visibility. Please modify the CSS or styling of the newsletter subscription form to improve text readability. This change will enhance user experience and increase the likelihood of successful newsletter subscriptions.

Thank you for addressing this issue promptly.

**Comment by MahendraDani** [comment]
@royalpinto007 
I already raised a PR for this issue. Please let me know if there are any changes!
https://github.com/Stoccoin-Official/Stoccoin-Website/pull/164

Thanks!
