### ISSUE TITLE
Style the login button and add hover effect

### ISSUE THREAD

**Issue by mukul314** [Stoccoin-Official/Stoccoin-Website#170]
The current login button does not look good, we can add some styling to make it more attractive. See the below video for more context:

https://github.com/Stoccoin-Official/Stoccoin-Website/assets/76463001/5ffeae16-aa06-497e-bfcd-d11b687fbc51

I'd like to work on this @royalpinto007 !!

**Comment by VishalJx** [comment]
Greeting,
I would like to help adding the mentioned feature. Kindly assign me the issue.
#gssoc2023

**Comment by 000626574705** [comment]
i want to style the login button along with changing color and adding effect
