### ISSUE TITLE
[FEAT]: Add a button which scrolls back to top

### ISSUE THREAD

**Issue by mukul314** [Stoccoin-Official/Stoccoin-Website#172]
Currently, there is no option for scrolling back to the top in the website. I'd like to have a button that scrolls back to the top when clicked upon. 
Look at the video below for more context :

https://github.com/Stoccoin-Official/Stoccoin-Website/assets/76463001/cbf5cdbb-8657-4897-a34f-fdb1ff26ae51

Please assign this issue to me @royalpinto007 !!

**Comment by Sandeep0306** [comment]
HIi, I want to add scroll to top Button which will become easy for user to navigate to top of the page . Please assign me this issue under GSSOC'23.
