### ISSUE TITLE
Uneven Look of Navbar

### ISSUE THREAD

**Issue by PrathamAsrani** [Stoccoin-Official/Stoccoin-Website#175]
I want to resign with more UI/UX to navbar please assign me #GSSOC23

**Comment by shubhisingh184** [comment]
I would like to improve the navbar and want to add some affects. Please assign this issue to me.

**Comment by khushi767** [comment]
Please assign me this issue under GSSOC'23

**Comment by SHIVA769** [comment]
please assign me  this issue under GSS0C

**Comment by Smit1324** [comment]
I would like to improve the Navbar as I am an UI/UX designer. So, please assign this issue to me under GSSOC 2023
