### ISSUE TITLE
Social names misaligned to the right of "Follow Us" section

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#18]
The "Follow Us" section on our website's landing page currently displays social media icons to the left, with the names of each social media platform aligned to the right.

To enhance the user experience and make it easier for visitors to identify the social media platforms we use, we need to fix this misalignment. The social media names should be vertically aligned under their corresponding icons.

This issue requires a minor design change to ensure that the alignment is correct. Let's prioritize this issue to improve the user experience and help visitors easily find our social media channels.

Please post before/after screenshots.

**Comment by Sachinvermaskv** [comment]
Hey, can I work on this issue?

**Comment by Sachinvermaskv** [comment]
I have created a pull request, please check it out- https://github.com/Stoccoin-Official/Stoccoin-Website/pull/19

**Comment by royalpinto007** [comment]
Thanks! @Sachinvermaskv
