### ISSUE TITLE
Creating login page for Stoccoin 

### ISSUE THREAD

**Issue by Adityamishra9719** [Stoccoin-Official/Stoccoin-Website#198]
Hi , @royalpinto007, I have seen the website and there is no Login page so, I want to add the login page for the website.

I will give an option for user to upload his/her image ,phone number ,email .

I want to make the login page as shown below-
![Screenshot 2023-05-24 154215](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/105539123/48c85a50-cde7-434b-b912-95364b6dcfc6)

Please assign me this issue.
my branch name will be  Adityamishra9719.

**Comment by MahendraDani** [comment]
@Adityamishra9719 There is already an exiting issue for this #159 
P.S : Please try to design this according to the website's color theme
Thanks!

**Comment by Adityamishra9719** [comment]
@MahendraDani as when this issue will assigned to me it will be made keeping in mind the color theme of website ,this only the demo for the login page not actual one.
