### ISSUE TITLE
Update Contribution Guidelines

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#2]
Currently, there are no clear guidelines in place for contributing to this project. This can make it difficult for new contributors to get started and can lead to inconsistencies in coding style and quality. To address this, we need to update our contribution guidelines to provide clear instructions on how to contribute code to the project. This will make it easier for new contributors to get involved and will help to maintain a high level of code quality across the project.

**Comment by Satyam2648** [comment]
Can you please assign this issue to me ?
