### ISSUE TITLE
Add Social Links to Footer Section

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#20]
The website currently does not have any social media links displayed in the footer section. Adding social links to the footer can greatly increase the website's engagement with visitors, allowing them to easily connect and follow the website's social media accounts. Additionally, having social links in the footer can also improve the website's SEO as it provides additional backlinks to social media profiles. Therefore, it is recommended to add social media links to the footer section of the website to improve user engagement and search engine optimization.

**Comment by nishchalmayur** [comment]
Hello, can I work on this issue?

**Comment by nishchalmayur** [comment]
I created a pull request, please review it from your side- https://github.com/Stoccoin-Official/Stoccoin-Website/pull/22

**Comment by royalpinto007** [comment]
Thanks! @nishchalmayur
