### ISSUE TITLE
Adding 404 error page 

### ISSUE THREAD

**Issue by PShreya16** [Stoccoin-Official/Stoccoin-Website#212]
**Description:**
I would like to suggest the **addition of an error page** to enhance the user experience of the application.

**Issue Type:** Enhancement

**Description:**
Currently, when an error occurs within the application, users are presented with a generic error message or redirected to a default error page. This can be frustrating for users as they are not provided with any specific information about the error or guidance on how to resolve it.

I propose adding a dedicated error page that provides clear and actionable information to users when an error occurs. This page should display a user-friendly error message, along with any relevant details about the error, such as error codes or stack traces if applicable. Additionally, it would be helpful to include suggestions or links to relevant resources that can assist users in troubleshooting or reporting the error.

By incorporating an error page, we can improve the overall user experience by providing better feedback and guidance in case of errors. It will help users understand what went wrong, potentially resolve the issue on their own, or provide more accurate information when reporting the error to support or the development team.

I'm willing to contribute to this feature by assisting in the design and development of the error page as it aligns with the project's goals and guidelines.

Thank you for considering this suggestion. I look forward to your feedback and the opportunity to contribute to the project.

**Labels:** enhancement, user experience, help wanted

**Comment by doppedheart** [comment]
i wanted to work on the error page .
can you guide me more on how the desgin will be and the error for which the error page will popup

**Comment by mukul314** [comment]
This issue has been raised already, see #111 !!

**Comment by mfatima05** [comment]
Please assign this issue to me under GSSoC'23

**Comment by Smit1324** [comment]
I have worked on similar projects. So please assign me this task under SSOC 2023
