### ISSUE TITLE
Feature: Enable the contact us Form 

### ISSUE THREAD

**Issue by AbhishekCS3459** [Stoccoin-Official/Stoccoin-Website#217]
Hey @royalpinto007  the contact us Form is not enabled and I want to work in this issue Please assign it to me.
I will enable that form such that any user can send his message using that form.

**Comment by Michelle031** [comment]
Please can I work on this issue, I have done numerous contact forms.

**Comment by mfatima05** [comment]
Please assign this issue to me under GSSoC'23

**Comment by royalpinto007** [comment]
We can work on this issue now, please submit a PR, thanks!

**Comment by Deepanshu0703** [comment]
This issue is inactive for a long time can you now assign this task to me @royalpinto007

**Comment by royalpinto007** [comment]
Sure @Deepanshu0703, please submit a PR, thanks :)
