### ISSUE TITLE
Need of Dark Theme 

### ISSUE THREAD

**Issue by urz-ahmed** [Stoccoin-Official/Stoccoin-Website#225]
Hello Project Maintainer,
I hope you are well. I'm impressed by your repo.
I want to contribute to it by adding a **dark theme** in your website.
Please assign me this issue under gssoc'23.

**Comment by mfatima05** [comment]
Please assign this issue to me under GSSoC'23

**Comment by 2020B1531074** [comment]
Please assigned me this issue

**Comment by ArjunKSoni** [comment]
Hello,
I hope you are well.
I want to contribute to this.
please assign me this issue under SSS

**Comment by royalpinto007** [comment]
Refer- https://github.com/Stoccoin-Official/Stoccoin-Website/issues/7
