### ISSUE TITLE
Missing Koo Social Media Name and Link in Footer

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#23]
I noticed that the Koo social media name and link are missing from our website's footer section. As Koo is an important platform for our target audience, it is essential that we include it in the footer for easy access.

**Comment by shivani037** [comment]
Hello can I work on this issue?

**Comment by royalpinto007** [comment]
Sure, please go ahead!

**Comment by shivani037** [comment]
I have created a pull request please review it-https://github.com/Stoccoin-Official/Stoccoin-Website/pull/24

**Comment by royalpinto007** [comment]
Thanks! @shivani037
