### ISSUE TITLE
Login/Signup page

### ISSUE THREAD

**Issue by Milan-rawat** [Stoccoin-Official/Stoccoin-Website#232]
I noticed that the repository does not have login and signup page I'll make a similar looking signup and login page, which will match with the theme.

Please assign this issue to me under GSSoC'23 @royalpinto007

**Comment by mfatima05** [comment]
Please assign this issue to me under GSSoC'23 @royalpinto007

**Comment by Visbhavesh** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by Milan-rawat** [comment]
@royalpinto007 I have raised this issue, pls assign me this
