### ISSUE TITLE
ADDING A FEEDBACK SECTION[GSSOC'23]

### ISSUE THREAD

**Issue by kharshita590** [Stoccoin-Official/Stoccoin-Website#245]

**Comment by kharshita590** [comment]
@royalpinto007 Sure

**Comment by royalpinto007** [comment]
Hi @kharshita590, 
Have you completed the work?
Please provide an update. It seems like you have been assigned for quite a while.
Thanks!

**Comment by ayushrathore111** [comment]
hii @kharshita590 @royalpinto007 is there any update on this issue. I wanna work on this if it's not assigned to anyone please assign to me 
thank you

**Comment by Dimple-01** [comment]
Hi ! @royalpinto007 I want to work on this issue. Please assign this to me.
