### ISSUE TITLE
"Connect with us" section should be moved above the License section in README file

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#25]
Currently, the "Connect with us" section appears below the License section in the README file, which may cause confusion for users who are trying to find ways to contact us. To improve the user experience and make it easier for users to connect with us, we suggest moving the "Connect with us" section above the License section in the README file.

**Comment by Bsodoge** [comment]
Can I work on this issue?

**Comment by royalpinto007** [comment]
Sure, please go ahead!
