### ISSUE TITLE
[GSSOC'23] Add a Leader board feature 

### ISSUE THREAD

**Issue by vivxsdb** [Stoccoin-Official/Stoccoin-Website#260]
Actually I want to provide a leaderboard of the top-performing traders So that users can come to know the experience of the other traders Can U please assign me this issue under GSSOC'23

**Comment by royalpinto007** [comment]
Hi @vivxsdb,
We don't think this thing is actually required, as we already get every single data from the contributors list. Additionally, we want to keep essential features in your readme. 
Thank you for understanding.
