### ISSUE TITLE
Create Forgot Password Page

### ISSUE THREAD

**Issue by AtharvaRaut2002** [Stoccoin-Official/Stoccoin-Website#266]
I noticed that the repository does not have Forgot Password page I'll make a similar looking forgot password page, which will match with the theme.

Please assign this issue to me under GSSoC'23 @royalpinto007

**Comment by AtharvaRaut2002** [comment]
#281

**Comment by royalpinto007** [comment]
The issue has been resolved at https://github.com/Stoccoin-Official/Stoccoin-Website/pull/281.
Thanks!
