### ISSUE TITLE
[Bug]: Login form 

### ISSUE THREAD

**Issue by vaibhav-xt** [Stoccoin-Official/Stoccoin-Website#272]
While exploring the website I found a bug under the login form. On clicking remember me the text checkbox not working should work and in the form, the label has a `for` attribute that should be replaced with `htmlFor`. 

I can make both the sign-up and login forms better. 

- [X] I am GSSOC Contributor 
- [X] I would like to work on this issue. 

![Screenshot (50)](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/90946899/2b0bf3e2-3c24-4ed0-8acb-ec38926bc8d4)

![Screenshot (48)](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/90946899/6fdf71ee-86da-4299-832a-5c5e8e7cff54)

**Comment by royalpinto007** [comment]
Cool, please submit a PR, thanks!

**Comment by suman-somu** [comment]
Making a PR

**Comment by royalpinto007** [comment]
Looks like it has already been addressed here- https://github.com/Stoccoin-Official/Stoccoin-Website/pull/265
Thanks for understanding!
