### ISSUE TITLE
Add contributors to the README.md

### ISSUE THREAD

**Issue by kunalnandre** [Stoccoin-Official/Stoccoin-Website#277]
I'd like to add the contributors profile images to the README.md, it will also keep updating itself as new contributors are added to project!

Example:

![241395433-f9d32232-d7f3-4c56-88b5-d2d609482a64](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/111383966/bb0e9631-3edb-47c6-938d-8f0f58f1f959)

Please have a look and assign this issue to me under GSSoC'23.

**Comment by royalpinto007** [comment]
Hi @kunalnandre, 
We don't think this thing is actually required, as we already get every single data from the contributors list. Additionally, we want to keep essential features in your readme. 
Thank you for understanding.
