### ISSUE TITLE
Create Issue buttons in the repo

### ISSUE THREAD

**Issue by dakshsinghrathore** [Stoccoin-Official/Stoccoin-Website#278]
Currently the contributor has to raise an issue from ground zero without any ***prebuilt buttons***, to gain a better understanding of the issue raised we can create custom issue buttons which will be ***visually appealing*** as well ***hassle free*** for the contributor to express their concern in an ***ordered manner*** .
 Here 👇 are some screenshots attached to give you a better understanding on what am up to 
### Currently

![Screenshot 2023-06-13 at 23-14-43 New Issue · SrijanShovit_carbonops-v2](https://github.com/SrijanShovit/carbonops-v2/assets/115932772/66a1f488-b745-4124-a218-92bbbc7307ef)

### To Come

![Screenshot 2023-06-13 at 23-19-39 New Issue · priyankarpal_ProjectsHut](https://github.com/SrijanShovit/carbonops-v2/assets/115932772/42addc33-f9fb-4eaf-b60a-fb7dab74844c)

***Kindly assign this issue to me*** @royalpinto007

**Comment by royalpinto007** [comment]
Cool, please submit a PR, thanks!

**Comment by royalpinto007** [comment]
Hey @dakshsinghrathore,  
Have you completed the work? 
Please provide an update. It seems like you have been assigned for quite a while.
Thanks!

**Comment by dakshsinghrathore** [comment]
Yep just give me one more day @royalpinto007

**Comment by dakshsinghrathore** [comment]
hey @royalpinto007 I have an idea ! 
can we add issue forms to the respective buttons , it will look something like this if a user clicks on the ***bug report*** button 👇

![Screenshot 2023-06-23 at 12-16-27 New Issue · dakshsinghrathore_htmltut](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/115932772/2b7e466e-33c4-4c97-a71c-486f15770f58)

It will be not only convenient for the contributor to raise an issue also it will save your time while going through it, do let me know if you want to edit some text boxes or add some checkboxes.
