### ISSUE TITLE
feat:  add dependabot

### ISSUE THREAD

**Issue by harmeetsingh11** [Stoccoin-Official/Stoccoin-Website#288]
### Is your feature request related to a problem? Please describe.
Keeping the  project's dependencies up to date can be a challenging task, if its done manually. 

### Describe the solution you'd like
We need to add `Dependabot` as it helps us to keep our dependencies up to date.  Once, Dependabot will be activated, it will start submitting PRs with any outdated dependency based on package.json file.

### Record
- [x] I agree to follow this project's Code of Conduct
- [x]  I'm a GSSoC'23 contributor
- [x]  I want to work on this issue

Please assign me this issue under gssoc23.
Thanks

**Comment by royalpinto007** [comment]
Pretty cool stuff, thank you for raising this @harmeetsingh11. please go ahead and submit a PR, thanks!
