### ISSUE TITLE
news page

### ISSUE THREAD

**Issue by ggauranshi-03** [Stoccoin-Official/Stoccoin-Website#290]
Created news page having multiple news cards with images, heading and read more link. The UI for the page is matching the website theme.

**Comment by royalpinto007** [comment]
Hi @ggauranshi-03,
Currently, we are working on the stocks and cryptocurrencies pages. Maybe you can take a look at those pages first. We will soon be working on the news page, which will have a specific design or perhaps fetch its content using an API or another method. 
Thank you for understanding.
