### ISSUE TITLE
Add a light and dark mode toggle button on the navbar 

### ISSUE THREAD

**Issue by karthiknadar1204** [Stoccoin-Official/Stoccoin-Website#303]
In my proposed feature, I wish to add a toggle switch on the navbar which will dynamically render light and dark mode on all the pages in the web page.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by royalpinto007** [comment]
Refer- https://github.com/Stoccoin-Official/Stoccoin-Website/issues/7
Thanks!
