### ISSUE TITLE
Adding contants to the support link on the navbar

### ISSUE THREAD

**Issue by karthiknadar1204** [Stoccoin-Official/Stoccoin-Website#304]
In my proposed solution, I think we could go with making it a pseudo contributors page in which we will first have a top section highlighting the maintainers of the project and in the lower half of the page, we could list out all the contributors in descending order of the number of commits.

All the info about the maintainers and the contributors will be dynamically rendered using the GitHub API and will be framed into evenly spaced and well designed cards, this is my suggestion.

If you have anything else you want to add to the page, please share it, would gladly work it out

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by royalpinto007** [comment]
We don't think this thing is actually required, as we already get every single data from the contributors list. Additionally, we want to keep essential features in your readme.
Thank you for understanding.
