### ISSUE TITLE
Incorrect homepage link in 404 page

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#311]
The `<a>` tag in the 404 page is not properly directing to the homepage. It is currently set to "", which doesn't work as expected.

**Comment by AtharvaRaut2002** [comment]
@royalpinto007  Assign this issue to me. I will work on it.

**Comment by AtharvaRaut2002** [comment]
@royalpinto007 Assign this issue to me under Gssoc'23. I'm intrested to work on it.
