### ISSUE TITLE
[Feature]: Add Code Spliting

### ISSUE THREAD

**Issue by Manice18** [Stoccoin-Official/Stoccoin-Website#322]
# Description
When the website is loaded, unnecessary components which are not required at that moment are loaded, thus reducing the optimisation of the website. 

# My Solution
I will like to implement the concept of code splitting with the help of React Lazy, suspense with proper fallback. This is help render the components only when it is required and thus optimising the website

**Comment by royalpinto007** [comment]
Cool @Manice18, please submit a PR, thanks!

**Comment by Manice18** [comment]
Ok, will get back soon

**Comment by Manice18** [comment]
@royalpinto007 can you check the pr ?
and also can you please add the gssoc label ?
