### ISSUE TITLE
start the project concurrently ie backend and frontend for developers

### ISSUE THREAD

**Issue by OmAgarwal8979** [Stoccoin-Official/Stoccoin-Website#328]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Using npm package to reach the solution

**Describe alternatives you've considered**

**Additional context**

**Comment by OmAgarwal8979** [comment]
Also to update the readme if feature addes

**Comment by Allen-Saji** [comment]
Hello there👋,
I wish to work on this issue, I have setup the project locally .
I'll install the concurrently package and add a run script to package.json in the main folder.
May I proceed?
