### ISSUE TITLE
Unneccessary loading of same component over and over again

### ISSUE THREAD

**Issue by AbhayKrSing** [Stoccoin-Official/Stoccoin-Website#337]
- Description

Navbar and footer component added in all component inside pages folder.
This causes unnecessary loading of unwanted over and over again.

- Screenshot
![component4](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/118283656/5e4d6b03-1eb6-4d59-8510-99dbe342ca83)
![component1](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/118283656/e3133a97-e433-4f28-9f38-a8f2b18cc58c)
![component2](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/118283656/7cbfee5f-fb72-4e94-9089-dc2eeb7f8c0b)
![component3](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/118283656/2e7fc639-55bb-4533-b5fc-4787601d8fa8)

And soon.

**Comment by AbhayKrSing** [comment]
Assign this issue to me under gssoc 2023. I m gssoc 2023 contributor

**Comment by royalpinto007** [comment]
Isn't this necessary?
Are your changes going to keep the same UI that other pages already have? If not, we can't work on this.
Please clarify, thanks!

**Comment by AbhayKrSing** [comment]
UI will not change because I will add that component to APP.js file.

**Comment by AbhayKrSing** [comment]
If you want me i can do a pull request , you can test that out on different branch.

**Comment by AbhayKrSing** [comment]
assign this to me.

**Comment by AbhayKrSing** [comment]
review it

**Comment by royalpinto007** [comment]
Addressed here- https://github.com/Stoccoin-Official/Stoccoin-Website/pull/343
