### ISSUE TITLE
[Style]: Improve Sign Up UI

### ISSUE THREAD

**Issue by rishuraj1** [Stoccoin-Official/Stoccoin-Website#345]
We might need to revamp the sign up form for better user experience.
Currently, it looks ordinary.

![image](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/47839626/1ac6de47-318f-4f5c-b4bc-11310b8a4679)

We can use tailwind css to its fullest potential to revamp the sign up form by 
- adding icons appropriate for fields
- adding images to make it interactive
- adding show/hide password functionality etc...

P.S.: Please assign this issue to me under GSSoC '23. Thank You!

**Comment by rishuraj1** [comment]
Thank you for the opportunity @royalpinto007 . Also, can you please add the approprate labels for gssoc 23 on this one and #344

**Comment by royalpinto007** [comment]
Sure :)

**Comment by rishuraj1** [comment]
hey @royalpinto007  , sorry to bother but, I believe that to be counted as contribution...the labels should be added to the PR merged. If you could add these labels to the PRs, that would be great for me.
Attaching links for the PRs for convenience:

#354    and   #352 

Thank you.

**Comment by royalpinto007** [comment]
Oops, I didn't notice that, thanks!
