### ISSUE TITLE
[Style]: Improve Footer section

### ISSUE THREAD

**Issue by rishuraj1** [Stoccoin-Official/Stoccoin-Website#346]
![image](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/47839626/56bd4b4e-a0c8-4956-8e0a-7c61723d4d32)

We can use tailwind css to its fullest potential to revamp the footer section by 
- rearranging icons of social media and paragraphs
- adding styles to icons and links
- additionally adding a link to this repo.

P.S.: Please assign this issue to me under GSSoC '23. Thank You!

**Comment by royalpinto007** [comment]
Link to the github repo issue is already being addressed, you can solve the remaining, thanks!

**Comment by Dimple-01** [comment]
@royalpinto007 I have worked on many projects of GSSoC in enhancing footer section. 
I want to work on this issue please assign this to me if allotted time to assignee is over.

 I will add something like this and much more. If you assign.

 
![Screenshot (126)](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/114878264/ce204db8-df2d-469a-9a86-74cd04ea1b6c)

**Comment by rishuraj1** [comment]
@Dimple-01  I was busy with other issues, although I totally intend to work on this issue now.

**Comment by royalpinto007** [comment]
Yeah cool @rishuraj1, no worries!
Also, @Dimple-01 you can try looking for other issues, thanks for understanding :)
