### ISSUE TITLE
[Bug]:  Adding a GITHUB icon in footer

### ISSUE THREAD

**Issue by marshadkhn** [Stoccoin-Official/Stoccoin-Website#348]
### Describe the bug

Hey @royalpinto007
While I was testing the website i found a small bug  in the footer section that we should include the `github icon` with other social media links

### To Reproduce

NONE

### Expected behavior

NONE

### Screenshots/Videos

![image](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/80325579/6866a5e2-4935-4743-842c-68ab5b1fea06)

### Additional context

NONE

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by marshadkhn** [comment]
Assign me this issue so that i can work on this

**Comment by marshadkhn** [comment]
@karenhernandeze It's assigned

**Comment by marshadkhn** [comment]
@lalitkumawat1m
![image](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/80325579/52ce5921-5c38-42fa-9738-cb88164d6f60)
**hope you get it you're not suppose to send PR**

**Comment by lalitkumawat1m** [comment]
I'm sorry @marshadkhn if my pr hurts you.
