### ISSUE TITLE
Improvement is needed in get in touch page.

### ISSUE THREAD

**Issue by Dimple-01** [Stoccoin-Official/Stoccoin-Website#358]
### Is your feature request related to a problem? Please describe.

**Issue**
Improvement is needed in get in touch page.

**Description**
I have noticed that the get in touch page is not much attractive and appealing.
I would make it more user engaging and user friendly.

### Describe the solution you'd like

**Current behavior**

![Screenshot (165)](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/114878264/a573b11b-e3ab-4a28-a32f-766bb394abe1)

**Desired behavior**

This is a rough idea that I created. I will make it much better once it is assigned to me.

![Screenshot (167)](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/114878264/8a2c4b19-af63-4cd0-ad29-57554dd24986)

### Additional context

I want to work on this issue .
Please assign this work to me under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by royalpinto007** [comment]
I don't think such a big change is necessary. You are completely changing the color system we are following, which doesn't make any sense. This won't be worked upon. 
Thanks for understanding!
