### ISSUE TITLE
Add Discord link for contribution discussions

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#36]
We have recently launched a Discord server for contributors to the Stoccoin's website on GitHub. The server is a great place for developers, designers, marketers, and other contributors to share their skills, collaborate on code, provide feedback, and contribute to the Stoccoin's project in meaningful ways. However, the link to the server is not currently included in the README file on GitHub, which makes it difficult for new contributors to find and join the server.

We propose to add a section to the README file that includes a link to the Discord server and encourages contributors to join the server for discussions and collaboration. Here is a possible section that could be added:

### Join our Discord server for contributors
We have a Discord server for contributors to the Stoccoin's website on GitHub. Join our community of developers, designers, marketers, and other contributors to share your skills, collaborate on code, provide feedback, and contribute to the Stoccoin's project in meaningful ways.

[Click here to join our Discord server](https://discord.gg/XVE7eaS9AA)

We believe that adding this section to the README file will make it easier for new contributors to find and join the Discord server, and encourage more collaboration and discussion among contributors. We would appreciate any feedback or suggestions on this proposal.

**Comment by rifleben** [comment]
Hello, I am attempting to add the Discord Server link per the issue (this is my first time contributing to a project, and I would greatly appreciate any feedback!). 

https://github.com/Stoccoin-Official/Stoccoin-Website/pull/37

**Comment by royalpinto007** [comment]
Hi @rifleben! 
Please go ahead and resolve it as needed. 
Let me know if you have any questions or need any additional information from me. 
Thanks for taking care of this!

**Comment by royalpinto007** [comment]
The issue has been resolved, thanks @rifleben :)
