### ISSUE TITLE
Add firebase authentication to the project

### ISSUE THREAD

**Issue by sumitkr2000** [Stoccoin-Official/Stoccoin-Website#364]
### Is your feature request related to a problem? Please describe.

Hey, I want to add firebase authentication to the project. Please assign me this issue. Thank you!

### Describe the solution you'd like

Add firebase

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by royalpinto007** [comment]
Please go ahead and submit a PR, thanks :)

**Comment by royalpinto007** [comment]
Solved here- https://github.com/Stoccoin-Official/Stoccoin-Website/pull/369
