### ISSUE TITLE
[Bug]: Minor Issue existed in documentation.yml File in GitHub ISSUE_TEMPLATES Folder 🐞🐞

### ISSUE THREAD

**Issue by NarendraKoya999** [Stoccoin-Official/Stoccoin-Website#385]
### Description:
- **`In documentation.yml File, Minor Errors existed in GitHub ISSUE_TEMPLATES Folder.`**

### To Reproduce

1. Go to 'https://github.com/Stoccoin-Official/Stoccoin-Website/blob/main/.github/ISSUE_TEMPLATE/documentation.yml'
4. See error on ` documentation.yml File.
`

### Expected behavior

- **To resolve above Issue and Expect to Original Documentation Template Appears on ISSUE_TEMPLATES List.**

### In documentation.yml File in GitHub ISSUE_TEMPLATES Folder

![stoccoin-2](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/84512164/e379ac3a-06dc-45ad-9bd4-142df90ee4ec)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by royalpinto007** [comment]
Fixed- https://github.com/Stoccoin-Official/Stoccoin-Website/pull/389
