### ISSUE TITLE
[Request]: Add styles.yml File for Raising Enhancement Requests in GitHub ISSUE_TEMPLATES

### ISSUE THREAD

**Issue by NarendraKoya999** [Stoccoin-Official/Stoccoin-Website#386]
### GSSOC'23 Contributor
**`1. styles.yml (Custom ISSUE_TEMPLATE):`**
The styles.yml file, on the other hand, serves as a custom ISSUE_TEMPLATE for issues related to coding style, code formatting, and linting rules within your GitHub repository. This template helps contributors or users report code style-related concerns or seek guidance on adhering to the project's coding standards.

The contents of styles.yml might include specific questions or prompts related to coding style, requesting users to provide examples of code snippets that need formatting adjustments or explanation. Additionally, you might include instructions on how to check code against the project's style guidelines and best practices.

### Describe the solution you'd like

- I want to `add Suitable yml format Code related with styles.yml File.`

### Additional context

- Hi @royalpinto007 . Please Review on this Issue. Thank You !

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by royalpinto007** [comment]
Fixed- https://github.com/Stoccoin-Official/Stoccoin-Website/pull/388
