### ISSUE TITLE
Fix command to start the Client and Server

### ISSUE THREAD

**Issue by tarun-hegde** [Stoccoin-Official/Stoccoin-Website#4]
The current readme file advises using ``  npm start  ``to run the frontend and backend on localhost, but the application doesn't run locally on using the command.

**Comment by royalpinto007** [comment]
Yes @webgeek2021, you can work on this issue. 
Please submit a pull request.

**Comment by royalpinto007** [comment]
@webgeek2021
The issue has been resolved- https://github.com/Stoccoin-Official/Stoccoin-Website/pull/6
Thanks!
