### ISSUE TITLE
Improve the UI of the Footer Section 

### ISSUE THREAD

**Issue by niranjan-kurhade** [Stoccoin-Official/Stoccoin-Website#40]
Need to fix the Colors and the font-weights of the Social links and about us text.
Also, need to fix the color of input-field in the newsletter section.

**Comment by royalpinto007** [comment]
Hey @niranjan-kurhade!

Thanks for raising this issue on GitHub. It's great to see community members taking an interest in our project and helping us improve it.

However, I noticed that your pull request doesn't follow the contribution guidelines that we've set out for this project. In order for us to efficiently review and merge your changes, it's important that you follow these guidelines.

Can you please take a moment to review the guidelines and make the necessary changes to your pull request? This will help us move forward with your contribution as quickly as possible.

Thanks again for your help and contributions to the project!

**Comment by royalpinto007** [comment]
Hey @niranjan-kurhade!

Thanks for raising this issue. It's great to see community members taking an interest in our project and helping us improve it.

However, I noticed that your pull request doesn't follow the contribution guidelines that we've set out for this project. In order for us to efficiently review and merge your changes, it's important that you follow these guidelines.

Can you please take a moment to review the guidelines and make the necessary changes to your pull request? This will help us move forward with your contribution as quickly as possible.

Thanks again for your help and contributions to the project!

**Comment by niranjan-kurhade** [comment]
This issue is solved with PR #41.
