### ISSUE TITLE
[DOCS] Missing Firebase Setup Instructions in Getting Started Guide

### ISSUE THREAD

**Issue by md61421** [Stoccoin-Official/Stoccoin-Website#415]
### Description

The current Getting Started guide does not include instructions for setting up Firebase, making it difficult for users to get started with the project.

### Screenshots

N/A

### Additional information

Proposed Changes -
Add detailed instructions for Firebase setup, including necessary configuration steps and dependencies.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by royalpinto007** [comment]
Please go ahead @md61421 :)

**Comment by md61421** [comment]
Thanks for assigning this issue I'll get the work done ASAP.
