### ISSUE TITLE
Adding Icons for Social Media Handles

### ISSUE THREAD

**Issue by mukul314** [Stoccoin-Official/Stoccoin-Website#42]
We can add social media icons along with the links, it will make the website visually appealing.
I'd like to work on this if you approve.
<img width="190" alt="2023-05-18 21_08_13-Stoccoin - Brave" src="https://github.com/Stoccoin-Official/Stoccoin-Website/assets/76463001/35f9cb3b-0146-491d-8f9e-48229bd2b027">

something like this maybe?

**Comment by royalpinto007** [comment]
Thank you @mukul314 for offering to work on the task of adding social media icons and links to our website. We appreciate your contribution! Before you begin, we have a specific requirement regarding the visual appearance of the icons. Please ensure that the icons follow our designated color scheme to maintain consistency with our UI.

If you are comfortable with this requirement, we would be happy to have you work on the task. Your attention to detail in aligning the colors will greatly enhance the website's overall design.

**Comment by royalpinto007** [comment]
Hi @RahulRana701! 

It seems like @mukul314 will be working on this issue. 

In open source, we strive to avoid clashes or conflicts from occurring. Collaboration and smooth coordination are essential to maintain a healthy and productive environment. Let's continue working together to address issues and enhance our project. Feel free to explore more tasks from our repository's issue queue.

You can check out our repository's issue queue for more issues. Thanks!

**Comment by mukul314** [comment]
> Thank you @mukul314 for offering to work on the task of adding social media icons and links to our website. We appreciate your contribution! Before you begin, we have a specific requirement regarding the visual appearance of the icons. Please ensure that the icons follow our designated color scheme to maintain consistency with our UI.
> 
> If you are comfortable with this requirement, we would be happy to have you work on the task. Your attention to detail in aligning the colors will greatly enhance the website's overall design.

I'm on it @royalpinto007 !!

**Comment by Ajeeth-07** [comment]
Is this issue still open? Can I work on this issue?

**Comment by Abhinavcode13** [comment]
can I work on this issue @royalpinto007 ?
