### ISSUE TITLE
Implement Responsive Navigation Bar and Sidebar

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#44]
**Description:**
Currently, the dashboard lacks a responsive navigation bar and sidebar. We need to implement a navigation system that adapts seamlessly to different screen sizes. This will enhance the user experience and ensure accessibility across devices. The responsive navigation bar and sidebar should maintain functionality and usability while providing a visually appealing layout.

**Expected Outcome:**
A fully responsive navigation bar and sidebar that seamlessly adjusts to different screen sizes, ensuring optimal user experience and accessibility. The implemented navigation system should be visually appealing and maintain full functionality across various devices.

**Additional Resources:**
Refer to the main issue https://github.com/Stoccoin-Official/Stoccoin-Website/issues/43 for additional design references or examples of effective notification systems.

**Comment by kartikayasija** [comment]
Please assign me this issue. I want to work on this under GSSOC'23

**Comment by sandeep0009** [comment]
i want to work upon this because i have knowledege of the technologies you are using and i can be more benefical for you

**Comment by khubaibkm** [comment]
Hello, I am a GSSOC'23 Contributor and want to work on this issue.

**Comment by ptharshit** [comment]
I want to work on this issue under GSSoC'23. Please assign me this.
