### ISSUE TITLE
Develop User Profile and Settings Pages

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#46]
**Description:**
Users need a dedicated profile page to view and manage their personal information within the dashboard. Additionally, we require a settings page where users can customize their dashboard experience, such as choosing a preferred theme, language, or notification preferences. The user profile and settings pages should have an intuitive layout and provide a seamless user experience.

**Expected Outcome:**
User profile and settings pages that allow users to view and update their information, customize their dashboard experience, and manage notification preferences. The pages should have an intuitive and user-friendly design, ensuring a seamless experience for users.

**Additional Resources:**
Refer to the main issue https://github.com/Stoccoin-Official/Stoccoin-Website/issues/43 for additional design references or examples of effective notification systems.

**Comment by ashutosh7i** [comment]
Hello sir,
my name is Aashutosh Soni, a Sophomore and a MERN Stack developer.
i am also a contributor at GSSOC and i found Stoccoin-Website project very intresting and would like to contribute to it.

**Comment by royalpinto007** [comment]
Hello @ashutosh7i, 

Thank you for reaching out and expressing your interest in contributing to the Stoccoin-Website project. It's great to hear that you find the project interesting. We welcome your contribution!

To proceed, please follow these steps:
1. Fork the Stoccoin-Website repository to your GitHub account.
2. Create a new branch in your forked repository to work on the changes related to the issue you want to address.
3. Implement the necessary updates and improvements in your branch.
4. Once you are satisfied with the changes, submit a pull request (PR) from your branch to the main repository.
5. Make sure to provide a clear and concise description of the changes you have made in the PR.
6. Follow the contribution guidelines mentioned in the project's repository.

Feel free to ask any questions if you need further clarification or assistance. We appreciate your contribution and look forward to reviewing your pull request.
