### ISSUE TITLE
Build Data Visualization Widgets (Charts, Tables, Maps)

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#47]
**Description:**
To enhance data analysis capabilities, we need to develop different types of data visualization widgets within the dashboard. These widgets should include charts, tables, and maps to present data in an intuitive and visually appealing manner. The widgets should support interactivity, customization, and dynamic data updates, allowing users to explore and analyze data effectively.

**Expected Outcome:**
Data visualization widgets (charts, tables, maps) that allow users to explore and analyze data effectively within the dashboard. The widgets should support interactivity, customization, and dynamic data updates for an enhanced data analysis experience.

**Additional Resources:**
Refer to the main issue https://github.com/Stoccoin-Official/Stoccoin-Website/issues/43 for additional design references or examples of effective notification systems.

**Comment by Abhinavcode13** [comment]
I can work upon this issue @royalpinto007 and can add the widgets. please assign this issue to me @royalpinto007
