### ISSUE TITLE
Update README: Correct backend server start command

### ISSUE THREAD

**Issue by Ahtaxam** [Stoccoin-Official/Stoccoin-Website#51]
in documentation how to run project, for running backend server it should be **node App.js** instead of **node server.js**.

Note: I would like to work on this issue

![Screenshot from 2023-05-19 23-50-09](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/64573767/afeb0220-ea4c-4281-87bb-573d26309584)

**Comment by royalpinto007** [comment]
Thanks @Ahtaxam for bringing up this issue. Please ensure that you follow the contribution guidelines when submitting a pull request :)

**Comment by Ahtaxam** [comment]
Make correction. Open PR

**Comment by royalpinto007** [comment]
Thanks @Ahtaxam :)

**Comment by Ahtaxam** [comment]
@royalpinto007 Can i further work on this project ? like implement all feature like login and other etc...

**Comment by royalpinto007** [comment]
Yeah, why not :)

**Comment by Ahtaxam** [comment]
ok. Now i Open issue for login functionality.
