### ISSUE TITLE
Implement Social Authentication

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#53]
**Description:**
As part of enhancing the registration and login experience on our project, we want to provide users with the option to authenticate using their social media accounts. This issue involves integrating social authentication with popular platforms such as Google, Facebook, and Twitter.

**Tasks:**
1. Research and select appropriate social authentication libraries or APIs that support the desired platforms (e.g., Passport.js with relevant strategies).
2. Implement the necessary server-side configurations and setup for each social authentication provider.
3. Create the user interface components for social login buttons, allowing users to choose their preferred social media platform.
4. Implement the authentication flow for each selected social media platform, handling user consent and fetching necessary user data (e.g., name, email).
5. Create user records in our system based on the authenticated data received from the social media platforms.
6. Implement session management and user authentication logic to securely handle social login sessions.
7. Ensure that appropriate error handling and fallback options are in place for cases where social authentication fails or is unavailable.
8. Update the user profile page to allow users to manage their connected social media accounts.

**Expected Outcome:**
Once this issue is completed, users will have the option to authenticate and register using their social media accounts. This will provide a seamless and convenient login experience, increasing accessibility and attracting a broader user base.

**Note to Contributors:**
If you're interested in working on this issue, please leave a comment below to let us know. Feel free to ask any questions or seek clarifications regarding the tasks or implementation details. We encourage you to fork the repository, create a new branch for your work, and submit a pull request once you have made the necessary changes. Thank you for your contributions!

**Comment by suravshrestha** [comment]
@royalpinto007 I want to work on this issue. Please assign me.
This issue is related to #52 so I want to work on both of them.

**Comment by tarun-hegde** [comment]
Hey @royalpinto007 , 
Could you assign me this issue?
I have worked on a similar login page before.
