### ISSUE TITLE
Populate Introduction to Stocks

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#55]
Populate file: stocks-introduction.md

Write the content for the introduction to stocks, covering the basics of the stock market, terminology, and how stocks function as investment vehicles. Provide clear and concise explanations to help beginner investors understand the concept of stocks.

Main issue: https://github.com/Stoccoin-Official/Stoccoin-Website/issues/10.

**Comment by sandeep0009** [comment]
hey i have knowledege of stocks would you please assign me this

**Comment by sabhisharma-ise** [comment]
Hey I'm a GSSOC'23 Contributor and would like to work on this issue.

**Comment by endeavourmonk** [comment]
I would like to work on this issue under GSSOC'23. Please assign it to me.

**Comment by bandevedant** [comment]
Considering my prior knowledge in trading and stock market I please ask you to assign this issue to me for the enhancement of the stoccoin community readers. under GSSoC'23 @royalpinto007
Thanks !
