### ISSUE TITLE
Populate Stock Market Basics

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#57]
Populate file: stock-market-basics.md

Write the content for the basics of the stock market, including stock exchanges, market indices, and the factors that impact stock prices. Provide clear explanations and examples to help beginners navigate the stock market.

Main issue: https://github.com/Stoccoin-Official/Stoccoin-Website/issues/10.

**Comment by suravshrestha** [comment]
@royalpinto007 I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by sabhisharma-ise** [comment]
Hey, Please provide me the opportunity to work on this issue!

**Comment by endeavourmonk** [comment]
I would like to work on this issue under GSSOC'23. Please assign it to me.

**Comment by Saloni581** [comment]
Could you please assign me this issue as a contributor of GSSOC'23.
