### ISSUE TITLE
Populate Cryptocurrency Market Basics

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#58]
Populate file: crypto-market-basics.md

Write the content for the basics of the cryptocurrency market, including cryptocurrency exchanges, market capitalization, and the role of decentralized finance (DeFi). Help beginners understand the unique aspects of the crypto market.

Main issue: https://github.com/Stoccoin-Official/Stoccoin-Website/issues/10.

**Comment by sandeep0009** [comment]
hey i want to work upon this issue would you like to give it to me

**Comment by royalpinto007** [comment]
Hi @sandeep0009!

That's great to hear that you're interested in working on the issue! We appreciate your enthusiasm and willingness to contribute.

While we don't have a formal assignment process in place, you're more than welcome to start working on it. Please feel free to submit a pull request (PR) with your proposed changes whenever you're ready. Remember to follow our contribution guidelines and ensure that your implementation aligns with the project's overall goals and design principles.

If you have any questions or need guidance during the development process, don't hesitate to reach out to the team or open an issue for discussion. We're here to support you throughout your contribution.

Thank you for your contribution, and we look forward to reviewing your PR!

**Comment by sandeep0009** [comment]
okay but what will be criteria of getting pull request .

**Comment by royalpinto007** [comment]
What do you mean by "getting pull request"?

**Comment by sandeep0009** [comment]
i mean to say what if other person will make same pr and if u wont assign me might it will create a dispute

**Comment by sandeep0009** [comment]
and also i requested for lots of documentation so can i make lots of request in a day

**Comment by royalpinto007** [comment]
Go ahead :)

**Comment by sandeep0009** [comment]
okay thanks please also reply on other documentation part too so that others wont waste their time on looking for same documentation .i hope u understand and will do all the work in the limited time period

**Comment by sandeep0009** [comment]
i had made  a pr request if u r able to see it then please look it and add it if you see it worth it or you wanted any changes u can tell me i will do it

**Comment by Saloni581** [comment]
Could you please assign this issue to me under GSSOC'23. I am very interested in it and can write very understandable content for beginners.
