### ISSUE TITLE
Populate Types of Stocks

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#59]
Populate file: types-of-stocks.md

Write the content describing the different types of stocks, such as common stocks, preferred stocks, and different classes of shares. Explain the characteristics, risks, and potential benefits associated with each type to guide beginner investors.

Main issue: https://github.com/Stoccoin-Official/Stoccoin-Website/issues/10.

**Comment by sandeep0009** [comment]
hey i want to work upon this issue would you please asign me

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by sabhisharma-ise** [comment]
Hey @royalpinto007 Can you assign this issue to me? I'm a GSSOC'23 Contributor
