### ISSUE TITLE
Populate Types of Cryptocurrencies

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#60]
Populate file: types-of-cryptocurrencies.md

Write the content exploring various types of cryptocurrencies, including Bitcoin, altcoins, stablecoins, and utility tokens. Provide an overview of the purposes, functionalities, and use cases for each type to help beginner investors understand the crypto landscape.

Main issue: https://github.com/Stoccoin-Official/Stoccoin-Website/issues/10.

**Comment by sandeep0009** [comment]
hey i want to work upon this task would you please asign me

**Comment by prakharSrivs** [comment]
@royalpinto007  I have create a PR for this issue PR #157 and would appreciate it if you could review it under GSSoC'23

**Comment by Rajeevjewar** [comment]
> hey i want to work upon this task would you please asign me

Do you understand this issue? Can you tell me about this issue.

**Comment by ayushrathore111** [comment]
hey @royalpinto007 please  assign this to me I understand what it needs and how to complete this task
thank you
