### ISSUE TITLE
Populate Fundamental Analysis

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#61]
Populate file: fundamental-analysis.md
 
Write the content for fundamental analysis for stocks and cryptocurrencies. Cover key factors to consider, such as financial statements, industry analysis, and management performance, to help beginners make informed investment decisions.
 
Main issue: https://github.com/Stoccoin-Official/Stoccoin-Website/issues/10.

**Comment by suravshrestha** [comment]
@royalpinto007 I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.
