### ISSUE TITLE
Populate Technical Analysis

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#62]
Populate file: technical-analysis.md

Write the content for technical analysis, explaining common chart patterns, indicators, and trend analysis techniques used in stock and cryptocurrency investing. Provide examples and guidelines for beginners to analyze price movements effectively.

Main issue: https://github.com/Stoccoin-Official/Stoccoin-Website/issues/10.

**Comment by suravshrestha** [comment]
@royalpinto007 I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by lalitkumawat1m** [comment]
I want to work on this issue as GSSoC'23 contributor
