### ISSUE TITLE
Populate Investment Strategies

### ISSUE THREAD

**Issue by royalpinto007** [Stoccoin-Official/Stoccoin-Website#64]
Populate file: investment-strategies.md

Write the content for different investment strategies for stocks and cryptocurrencies, such as value investing, growth investing, and dollar-cost averaging. Explain the principles and considerations behind each strategy to assist beginners in developing their investment approach.

Main issue: https://github.com/Stoccoin-Official/Stoccoin-Website/issues/10.

**Comment by suravshrestha** [comment]
@royalpinto007 I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.
