### ISSUE TITLE
Implement Dark Mode Feature for Improved User Experience

### ISSUE THREAD

**Issue by dev-sumukha** [Stoccoin-Official/Stoccoin-Website#7]
Add a dark mode feature to enhance the UI experience at low light

**Comment by royalpinto007** [comment]
Hi @dev-sumukha,
I wanted to express my gratitude for bringing up the topic of implementing a dark mode feature for our website. 
I believe this is an important and necessary feature that will greatly improve the user experience, especially for those who access our website in low-light settings.

**Comment by Shoetan** [comment]
Hi, @royalpinto007 is this issue still open? I will like it assigned to me.

**Comment by royalpinto007** [comment]
Hey @Shoetan, 
Yes, please go ahead and solve it :)

**Comment by shivaniyuvrajyadav** [comment]
hey @royalpinto007 This issue has been inactive for a long time
I would like to work on this issue
Please assign me this issue under GSSOC'23

**Comment by royalpinto007** [comment]
Yeah cool, please submit a PR, thanks!
