### ISSUE TITLE
Adding Favicon

### ISSUE THREAD

**Issue by tarun-hegde** [Stoccoin-Official/Stoccoin-Website#87]
Description:
I have identified the need to add a favicon to the website. A favicon is a small icon that appears in the browser tab or bookmark bar, providing visual branding and improving user experience. Currently, the website lacks a favicon, and it is important to address this issue to enhance our brand identity and improve user recognition.
@royalpinto007 kindly assign the issue to me as i can resolve it.

**Comment by royalpinto007** [comment]
Hey @tarun-hegde, thank you for bringing this to our attention! 
We appreciate your contribution. Could you please work on solving the issue and submit a pull request? 
Once you do, I'll gladly review it and provide feedback. 
Thank you again for your help!
