### ISSUE TITLE
Improving Responsiveness of Hero Section

### ISSUE THREAD

**Issue by kartikayasija** [Stoccoin-Official/Stoccoin-Website#90]
Task:
We have identified a need to enhance the responsiveness of the Hero section in our project. Currently, the Hero section does not adapt optimally to different screen sizes, resulting in suboptimal user experiences on certain devices or viewport sizes.

Note: It is important to refer to our contribution guidelines to align with the project's standards and ensure a smooth collaboration process.

We look forward to your valuable contributions in improving the responsiveness of the Hero section. Let's create an outstanding user experience together! If you have any questions or need further clarification, please feel free to reach out. Happy coding!

<img width="307" alt="image" src="https://github.com/Stoccoin-Official/Stoccoin-Website/assets/115306535/f207f347-3a7e-4097-b98f-99bd97246640">

**Comment by anuHait** [comment]
I would like to work on this issue

**Comment by royalpinto007** [comment]
Hi @anuHait,
It appears that both @kartikayasija and @tarun-hegde are doing their best to resolve this matter. Therefore, I kindly request you to address another issue from the queue. 
Thank you!
