### ISSUE TITLE
Adding Dark Mode to the Website

### ISSUE THREAD

**Issue by JatinBisht2308** [Stoccoin-Official/Stoccoin-Website#92]
Description: Our website currently lacks a dark mode feature, which has become increasingly popular and sought-after by users. Dark mode offers a visually appealing alternative to the default light mode, providing better readability, reduced eye strain, and improved user experience, especially in low-light environments.

Please assign this issue to me so that I can start working on it asap. 
And also please add the gssoc23 label on this issue as I am gssoc23 contributor.
Thank you so much @royalpinto007

**Comment by JatinBisht2308** [comment]
@royalpinto007 sir login functions and navbar items are not working is that the case for everyone or I have done something wrong while using it.

**Comment by royalpinto007** [comment]
Yes, we are still working on it. 
For now, please try to implement the dark mode on the landing page, and that's enough. 
Thanks! :)

**Comment by prashant744** [comment]
I  can work on this issue under gssoc 23 contribution ?

**Comment by JatinBisht2308** [comment]
@royalpinto007 ok sir thank you 
@prashant744 this is issues is assigned to me you can create you own issue or you can work on other issue.

**Comment by rishuraj1** [comment]
Hey, @JatinBisht2308  are you still working on this one ? If not, @royalpinto007  can you please assign this to me, I have experience in implementation of dark mode using tailwind. Thank You.

**Comment by royalpinto007** [comment]
We still need to work on responsive website, since the change has only been done for the desktop website!

**Comment by rishuraj1** [comment]
@royalpinto007  yes, I will start working as soon as possible.  Also, could you please add labels for my contribution. Thank You !

**Comment by royalpinto007** [comment]
For sure!
