### ISSUE TITLE
Add New Navbar Routes to enable Linking to New Pages

### ISSUE THREAD

**Issue by tarun-hegde** [Stoccoin-Official/Stoccoin-Website#94]
Currently, the website's navigation bar (navbar) is missing routes to link to newly created pages. To improve user experience and provide easy access to these pages, we need to add new navbar routes. This will ensure that users can easily navigate between different sections of our website.

**Comment by Arka90** [comment]
Hey I would like to work on that please assign it to me

**Comment by royalpinto007** [comment]
Hi @Arka90! 
Sure, please submit a PR. 
Thanks!

Also thanks to @tarun-hegde for bringing this up :)

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by lalitkumawat1m** [comment]
I want to contribute to this issue as @GSSOC'23 participate
Please assign it to me. Thank you.

**Comment by royalpinto007** [comment]
Hey @Arka90, have you completed the task yet?
We need to get it implemented ASAP, as because of this, we haven't started working on other stuffs yet. 
Please make sure you complete it at the earliest. 
Thanks for understanding :)

**Comment by royalpinto007** [comment]
@Sathvik902 @lalitkumawat1m 
Since the issue has already been assigned to @Arka90 and as you might be knowing we try to avoid having conflicts in the open source world, it won't be possible for me to assign it to you guys, however if @Arka90 delays it for long, maybe you can just give a shot in solving this! (for now, you can look for other issues present on the issue queue)
Thanks!

**Comment by Sathvik902** [comment]
@royalpinto007 Sure!

**Comment by Arka90** [comment]
hey @royalpinto007 I have submitted the PR please review it and let me know

**Comment by royalpinto007** [comment]
Hey @Arka90,
The PR that you submitted doesn't resolve the issue. We don't want to link the page to the landing page itself!

**Comment by Vaibhav-Sharma010204** [comment]
@royalpinto007  i would love to work on this kindly assign this to me

**Comment by royalpinto007** [comment]
Hey @Vaibhav-Sharma010204, 
Please submit a pull request. (it's fine if you aren't assigned)
Thanks!

**Comment by royalpinto007** [comment]
The issue has been solved here: https://github.com/Stoccoin-Official/Stoccoin-Website/pull/182. Thanks, @MahendraDani :) 
(Sharing it here so that others can refer in case they didn't know.)
