### ISSUE TITLE
Implement Login Functionality

### ISSUE THREAD

**Issue by Ahtaxam** [Stoccoin-Official/Stoccoin-Website#95]
We should take our project to advanced level and implement login , logout functionality.
**Note**: Would like to work on this issue.

**Comment by royalpinto007** [comment]
Main Issue: https://github.com/Stoccoin-Official/Stoccoin-Website/issues/50
We are still working on the design part, you can then add the functionality :)
Thanks!

**Comment by royalpinto007** [comment]
Oops! I've noticed that an issue for this problem has already been created at https://github.com/Stoccoin-Official/Stoccoin-Website/issues/53.

However, if you're interested, feel free to give it a try and contribute to solving the issue. Your efforts would be greatly appreciated. Thank you!

**Comment by Ahtaxam** [comment]
OK. O'll start working on this by today.

**Comment by Ahtaxam** [comment]
@royalpinto007 what should be form field while registering a user like userName, email, and password is enougn? or someone else.

**Comment by royalpinto007** [comment]
@Ahtaxam 
Let's discuss this in the existing issue instead of here.
Thanks for understanding!
